### ISSUE TITLE
seek help

### ISSUE THREAD

**Issue by coderlrj** [FBBL/fbbl#9]
I have no idea that how to change it to apply for higher dimension lwe instance

**Comment by AlessandroBudroni** [comment]
When you compile with cmake, you use for example the following:

`cmake -D MAX_N=20 -D BUILD_FFT=OFF ..`

In this way you set the maximum dimension to 20. The tests will however run in dimension 10.

**Comment by coderlrj** [comment]
but how can I use this cpp to compute my own sample data, I cannot find the data interface. I am sorry to ask have this project completed?

**Comment by AlessandroBudroni** [comment]
So this is another question. The best way to get to understand how the library works is to look at the tests.

For example in the file "test_smooth_lms_LF2_fwht_10_101_005.c", line 77-79 you can see how a new LWE instance is generated.

This is an ongoing project and servers for research purposes. We have very limited resources to make it more user-friendly.

**Comment by coderlrj** [comment]
That is the problem! I have some 40 dimension lwe sample  txt data. I want to use this to compute it! I have been trying for three days but still solve it

**Comment by AlessandroBudroni** [comment]
It is not clear what you mean when you say "compute", I guess you mean "run BKW algorithm". If you have an external LWE instance, there are two options:
1) you already generated millions of samples (needed since we are in dimension 40) - this case is not really handled by the library, but one can implement some workaround
2) you have a few samples and you want to use sample amplification to generate more (at the cost of increasing the error rate). In this case you should look at [this test](https://github.com/FBBL/fbbl/blob/master/test/test_smooth_lms_sample_ampli_fwht_10_101_01.c) that amplifies the samples of the LWE instance in /testVectors/LWE_10_101_01.txt.

**Comment by coderlrj** [comment]
Thanks for your patience! What is the meaning of 'one can implement some workaround'?

**Comment by AlessandroBudroni** [comment]
There I meant that one would need to implement a function that turns your samples into a format that is readable by the library, and so generate a data file that is of the kind generated by the library. This is in order to read the samples.

**Comment by coderlrj** [comment]
Hi，I came again! This time I want to know that have you ever test 40 dimension instance? If yes, how long it took?

**Comment by AlessandroBudroni** [comment]
Hi,

we tested instances up to dimension 45. You can find the results in the paper linked in the Readme file. Mind that these results are by far not the best achievable. We are indeed working on optimising the code and we already reduced the running time by a lot.

I am closing this issue since this is not an "issue" with the code but a different kind of question. Feel free to write me by email for other questions like this.
